name: action

on:
  pull_request:
  workflow_dispatch:

jobs:
  action:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        pipx-version: ["1.0"]
        poetry-version: ["1.1"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: fredrikaverpil/setup-pipx@set-envs
        with:
          pipx-version: "1.0"
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry/virtualenvs
            ../pipx_venv
            ~/.local/pipx
            ~/.local/bin
            ~/.local/Scripts
          key: ${{ runner.os }}-py-${{ matrix.python-version }}-pipx-${{ matrix.pipx-version }}-poetry-${{ matrix.poetry-version }}-${{ hashFiles('poetry.lock') }}

      - run: env

      - run: pipx install poetry==${{ matrix.poetry-version }}
        if: steps.cache.outputs.cache-hit != 'true'

      - run: pipx install creosote
        if: steps.cache.outputs.cache-hit != 'true'

      - run: poetry install --no-dev
        if: steps.cache.outputs.cache-hit != 'true'

      - run: pipx ensurepath

      - run: ls ~/.local/pipx
        if: runner.os != 'Windows'
      - run: ls ~/.local/bin
        if: runner.os != 'Windows'

      - run: ls ~\.local\pipx
        if: runner.os == 'Windows'
      - run: ls ~\.local\Scripts
        if: runner.os == 'Windows'

      - run: poetry env info
      - run: creosote
